name: Build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fabricar APK
        uses: kivy/buildozer-action@v1.2.3
        with:
          buildozer_version: stable
      - name: Subir Archivo
        uses: actions/upload-artifact@v4
        with:
          name: CapoPlay-APK
          path: bin/*.apk
